import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const SAMPLE_LISTINGS = [
  // 1. Off-Plan Listings
  {
    title: '2 BR Luxury Apartment - Emaar Beachfront',
    location: 'Dubai Marina',
    community: 'Dubai Marina',
    property_type: 'Apartment',
    transaction_type: 'Residential Sale',
    listing_status: 'Off-Plan',
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1250,
    price_aed: 1200000,
    price_label: 'AED 1.2M',
    expected_roi: 8.5,
    developer: 'Emaar',
    completion_date: '2028-06-30',
    description: 'Premium off-plan apartment with full marina views and smart home features.',
    featured: true,
    status: 'Available',
  },
  {
    title: '3 BR Villa - Damac Hills',
    location: 'Damac Hills',
    community: 'Damac Hills',
    property_type: 'Villa',
    transaction_type: 'Residential Sale',
    listing_status: 'Off-Plan',
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2100,
    price_aed: 1850000,
    price_label: 'AED 1.85M',
    expected_roi: 7.2,
    developer: 'DAMAC',
    completion_date: '2027-12-31',
    description: 'Spacious villa with private garden and community amenities in highly sought-after development.',
    featured: true,
    status: 'Available',
  },
  // 2. Ready Residential Properties
  {
    title: '1 BR Modern Studio - Downtown Dubai',
    location: 'Downtown Dubai',
    community: 'Downtown Dubai',
    property_type: 'Apartment',
    transaction_type: 'Residential Sale',
    listing_status: 'Ready',
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 680,
    price_aed: 650000,
    price_label: 'AED 650K',
    expected_roi: 6.8,
    developer: 'Emaar',
    description: 'Ready-to-move studio with Burj Khalifa views. Perfect for investors.',
    featured: true,
    status: 'Available',
  },
  {
    title: '4 BR Family Home - Dubai Hills Estate',
    location: 'Dubai Hills Estate',
    community: 'Dubai Hills Estate',
    property_type: 'Villa',
    transaction_type: 'Residential Sale',
    listing_status: 'Ready',
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 3200,
    price_aed: 3500000,
    price_label: 'AED 3.5M',
    expected_roi: 5.5,
    developer: 'Emaar',
    description: 'Spacious villa with premium finishes, pool, and garden in gated community.',
    featured: true,
    status: 'Available',
  },
  // 3. Ready Commercial Properties
  {
    title: 'Office Space - Business Bay',
    location: 'Business Bay',
    community: 'Business Bay',
    property_type: 'Office',
    transaction_type: 'Commercial Sale',
    listing_status: 'Ready',
    bedrooms: 0,
    bathrooms: 2,
    area_sqft: 1500,
    price_aed: 2400000,
    price_label: 'AED 2.4M',
    expected_roi: 7.8,
    developer: 'Damac',
    description: 'Prime office space with flexible layout in high-traffic commercial hub.',
    featured: true,
    status: 'Available',
  },
  {
    title: 'Retail Shop - The Dubai Mall',
    location: 'Downtown Dubai',
    community: 'Downtown Dubai',
    property_type: 'Retail',
    transaction_type: 'Commercial Sale',
    listing_status: 'Ready',
    bedrooms: 0,
    bathrooms: 1,
    area_sqft: 800,
    price_aed: 1800000,
    price_label: 'AED 1.8M',
    expected_roi: 9.2,
    developer: 'Emaar',
    description: 'High-footfall retail space in iconic shopping destination.',
    featured: true,
    status: 'Available',
  },
  // 4. Rental Commercial Properties
  {
    title: 'Office Suite - DIFC',
    location: 'Downtown Dubai',
    community: 'DIFC',
    property_type: 'Office',
    transaction_type: 'Commercial Lease',
    bedrooms: 0,
    bathrooms: 3,
    area_sqft: 2000,
    price_aed: 180000,
    price_label: 'AED 180K / year',
    rental_yield: 7.5,
    developer: 'DIFC Developments',
    description: 'Modern office suite in Dubai International Financial Centre.',
    featured: false,
    status: 'Available',
  },
  {
    title: 'Warehouse Space - Jebel Ali',
    location: 'Jebel Ali',
    community: 'Jebel Ali',
    property_type: 'Warehouse',
    transaction_type: 'Commercial Lease',
    bedrooms: 0,
    bathrooms: 2,
    area_sqft: 5000,
    price_aed: 250000,
    price_label: 'AED 250K / year',
    rental_yield: 8.3,
    developer: 'Jebel Ali Free Zone',
    description: 'Large warehouse with dock access, ideal for logistics operations.',
    featured: false,
    status: 'Available',
  },
  // 5. Rental Residential Properties
  {
    title: '2 BR Furnished Apartment - JBR',
    location: 'Jumeirah Beach Residence',
    community: 'JBR',
    property_type: 'Apartment',
    transaction_type: 'Residential Rental',
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1100,
    price_aed: 85000,
    price_label: 'AED 85K / year',
    rental_yield: 6.5,
    developer: 'Emaar',
    description: 'Fully furnished 2BR apartment with beach access and community amenities.',
    featured: true,
    status: 'Available',
  },
  {
    title: '3 BR Villa - Arabian Ranches',
    location: 'Arabian Ranches',
    community: 'Arabian Ranches',
    property_type: 'Villa',
    transaction_type: 'Residential Rental',
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2400,
    price_aed: 150000,
    price_label: 'AED 150K / year',
    rental_yield: 5.8,
    developer: 'Emaar',
    description: 'Spacious villa in exclusive gated community with resort-style amenities.',
    featured: true,
    status: 'Available',
  },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Admin access required' }, { status: 403 });
    }

    const created = await base44.asServiceRole.entities.Property.bulkCreate(SAMPLE_LISTINGS);
    
    return Response.json({ 
      success: true, 
      message: `Created ${created.length} sample listings across all 5 categories`,
      count: created.length,
      categories: {
        'Off-Plan': 2,
        'Ready Residential': 2,
        'Ready Commercial': 2,
        'Rental Commercial': 2,
        'Rental Residential': 2,
      }
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});